name: 🚀 Deploy index.php automatically

on:
  push:
    branches:
      - main  # ou master si c'est ta branche

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Cloner le code
        uses: actions/checkout@v3

      - name: 🔐 Configurer la connexion SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Déployer via rsync
        run: |
          rsync -avz --delete index.php ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/

